### ISSUE TITLE
Probeer geen divjes te gebruiken alleen als je er wat functioneels mee gaat doen

### ISSUE THREAD

**Issue by modous** [itsValyria/the-client-website#1]
https://github.com/itsValyria/the-client-website/blob/9d98f562da1eb4693ee25813b21b68404900f661/index.html#L52

**Comment by itsValyria** [comment]
Fixed!
https://github.com/itsValyria/the-client-website/blob/2c50ad209bbfe00f93cad9bc9c8df98ba67c8f13/index.html#L52
