### ISSUE TITLE
Probeer duidelijke classnamen te gebruiken

### ISSUE THREAD

**Issue by modous** [itsValyria/the-client-website#2]
https://github.com/itsValyria/the-client-website/blob/9d98f562da1eb4693ee25813b21b68404900f661/index.html#L66

**Comment by itsValyria** [comment]
Opgelost!

https://github.com/itsValyria/the-client-website/blob/2c50ad209bbfe00f93cad9bc9c8df98ba67c8f13/index.html#L66
